Repository walkingWithPuppy/FE_walkingWith7Puppy, pull requests merged in 2023-05, with the labels that each got.

#5 [Feat/layout] Header, Footer 구현, path 상수화
  src/assets/LogoIcon.svg
  src/component/Footer.js
  src/component/Header.js
  src/pages/Home.js
  src/shared/AnimatedRouter.js
  src/shared/GlobalStyle.js
  src/shared/Layout.js
  src/shared/Router.js
  src/shared/constants.js
Labels: Layout

#14 [Feat/home] Homepage 구현
  package-lock.json
  package.json
  public/index.html
  src/assets/HeaderImage.png
  src/assets/Section02SmileIcon.svg
  src/assets/Section2BoneIcon.svg
  src/assets/Section2DogIcon.svg
  src/assets/Section2FootIcon.svg
  src/assets/Section3ExampleImage.png
  src/assets/Section3ExampleImage2.png
  src/assets/Section3ExampleImage3.png
  src/component/home/HomeSection01.jsx
  src/component/home/HomeSection02.jsx
  src/component/home/HomeSection03.jsx
  src/component/home/HomeSection04.jsx
  src/component/home/Section02Card.jsx
  src/component/home/Section03Post.jsx
  src/hooks/useScrollFadeIn.js
  src/pages/Home.js
  src/shared/GlobalStyle.js
Labels: Layout, Feat

#19 Feat/board 게시판 검색(지역)기능 추가, axios url 통일
  db.json
  src/api/axios.js
  src/component/board/List.jsx
  src/component/comment/CommentItem.jsx
  src/redux/modules/boardsSlice.js
  src/redux/modules/commentsSlice.js
Labels: Feat
